# Generated by Django 5.2.3 on 2025-07-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='iin',
        ),
        migrations.AddField(
            model_name='testresult',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='users.applicant'),
            preserve_default=False,
        ),
    ]
