# Generated by Django 5.2.3 on 2025-07-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_testresult_iin_testresult_applicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Test Result', 'verbose_name_plural': 'Test Results'},
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='date_taken',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default='John', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='level',
            field=models.CharField(choices=[('A0', 'Beginner'), ('A1', 'Pre-Intermediate'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced')], max_length=2),
        ),
    ]
