# Generated by Django 5.2.3 on 2025-07-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('applicant', 'level')},
        ),
    ]
