# Generated by Django 5.2.3 on 2025-07-05 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_testresult_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(help_text='Enter only letters, spaces, and hyphens', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name can only contain letters, spaces, and hyphens.', regex='^[a-zA-Zа-яА-ЯёЁ\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='iin',
            field=models.CharField(help_text='Enter exactly 12 digits (e.g., 001001001001)', max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_iin', message='IIN must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(help_text='Enter only letters, spaces, and hyphens', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name can only contain letters, spaces, and hyphens.', regex='^[a-zA-Zа-яА-ЯёЁ\\s\\-]+$')]),
        ),
    ]
