# Generated by Django 5.1.6 on 2025-07-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='current_level',
            field=models.CharField(choices=[('A1', 'Elementary'), ('A2', 'Pre-Intermediate'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced')], default='A1', max_length=2),
        ),
    ]
