# Generated by Django 5.1.6 on 2025-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        ('users', '0007_delete_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='level',
            field=models.CharField(choices=[('A0', 'Beginner'), ('A1', 'Pre-Intermediate'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced')], default='A1', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='testsession',
            unique_together={('applicant', 'level', 'started_at')},
        ),
    ]
